name: todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.6.1
  device_preview: ^1.2.0
  easy_localization: ^3.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
